### PR TITLE
Rename IPQs to PSEs

### PR DESCRIPTION
**Pull request by nancy-harris**
Changes the name of the problems from IPQs to PSEs. Addresses this ticket: https://app.asana.com/0/1201700438643002/1205003469615033

### CODE REVIEW

**Review by anselrognlie — APPROVED** [review]
LGTM. The only other thing I see that we might want to change is in the main repo README.md,  these are described as "interview practice question assignments". For consistancy, we could update that to "problem solving exercise assignments."

**Comment by kelsey-steven-ada** [comment]
We also refer to "Interview Practice Questions" in one of the CS-Fundamentals-Internship pages `01-algorithms/01-algorithms.md`. 

> "...Notice the similarity to Problem Solving Exercises in the classroom portion of Ada and their equivalent, Interview Practice Questions, in the current unit portion..."

With this PR's changes, we may want to remove that line to avoid confusion.

**Comment by nancy-harris** [comment]
> 
Great catch! I just did a search for "IPQ" in the repo and missed that. I can add that change.

**Review by anselrognlie — APPROVED** [review]
👍

**Pull request merged**
